### ISSUE TITLE
Switch implementation to use action_from_request plugin hook

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-auth-existing-cookies#13]
This can integrate directly with https://datasette.readthedocs.io/en/latest/authentication.html#authentication now

**Comment by jsfenfen** [comment]
Just checking in, I think you mentioned this issue needed to be resolved for datasette-auth-existing-cookies to work on google cloudrun, is that correct? I set up a cloudrun instance on a subdomain that matches my main domain, and while the cookie is received it doesn't seem to stop anyone from accessing it. I can get the plugin working on localhost (with modified login addresses on localhost), which confused me a bit. More broadly speaking, is this still the way forward on third-party auth for cloudrun ?

**Comment by simonw** [comment]
OK, I'm finally looking at this today. Goals:

- Ditch the `asgi_wrapper` hook in favour of `actor_from_request`: https://docs.datasette.io/en/stable/plugin_hooks.html#actor-from-request-datasette-request
- Ditch the weird `appdirs` / `secrets` stuff, since Datasette has its own signed cookie mechanism now

**Comment by simonw** [comment]
https://simonwillison.net/user-from-cookies/ is now running on my personal domain:

```python
@never_cache
def user_from_cookies(request):
    if not request.user.is_authenticated:
        return JsonResponse({})
    return JsonResponse(
        {
            "id": request.user.id,
            "username": request.user.username,
            "name": request.user.get_full_name(),
            "is_staff": request.user.is_staff,
            "is_superuser": request.user.is_superuser,
        }
    )
```
I also had to change Django's session cookie settings to make it available to subdomains:
```python
SESSION_COOKIE_DOMAIN = ".simonwillison.net"
```
I actually used an environment variable for that:
```python
if os.environ.get("SESSION_COOKIE_DOMAIN"):
    SESSION_COOKIE_DOMAIN = os.environ["SESSION_COOKIE_DOMAIN"]
```

**Comment by simonw** [comment]
The very simple implementation in that branch totally works! https://github.com/simonw/datasette-auth-existing-cookies/blob/25120f13d2b5447a4db4f0955c06309a3825203f/datasette_auth_existing_cookies/__init__.py#L1-L17

Biggest catch: it currently makes an API call to that backend API on every single request to Datasette, which I think is an unreasonable performance overhead.

Instead I'd like to cache the value that comes back from that API for a configured number of seconds - defaulting to 30.

I could use `cachetools.TTLCache` for that: https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache

**Comment by simonw** [comment]
I'm going to be able to delete SO MUCH code here.

**Comment by simonw** [comment]
Bumping this up - it's been too long!

**Comment by simonw** [comment]
Rather than using `cachetools` I'm inclined to use my own signed cookie for the don't-hit-on-every-request thing.

I'm going to try using the existing `ds_actor` cookie with the mechanism described here: https://docs.datasette.io/en/stable/authentication.html#including-an-expiry-time

**Comment by simonw** [comment]
I'm not sure replacing the `asgi_wrapper` with `actor_from_request` is actually going to work. There are a few things that this needs that the `actor_from_request` plugin hook cannot provide:

- Return a forbidden message if the user does not have permission
- Redirect the user to the login page (actually I can probably do that with the `forbidden()` plugin hook)
- #16

I can still benefit from Datasette 0.44+ authentication by using the `ds_actor` cookie, but I'm likely going to still need to use the `asgi_wrapper` hook to get the other functionality.


... or am I? The ultimate goal of this plugin is to allow cookies from an existing domain to also authenticate the user for Datasette. So maybe I'm overthinking this and functionality such as #16 should be pulled out of this entirely?

**Comment by simonw** [comment]
Of course, that's why I was looking at `cachetools` in the first place: it lets m implement this using just the `actor_from_request` hook.

**Comment by simonw** [comment]
Quick check on how well maintained `cachetools` is.

https://pypistats.org/packages/cachetools shows 2.2m downloads a day, documentation looks good, MIT licensed, continuously maintained since 2014, last commit within a few weeks. Looks like a good dependency.

**Comment by simonw** [comment]
Since this will be an almost complete redesign of the plugin, including breaking some existing features (like the `?next=` bit), I'm going to ship this as a 1.0alpha and eventually release it as a 1.0 once I've tested it out in one of my own projects.

**Comment by simonw** [comment]
I still want three pieces of configuration:

- `api_url` - same as now. If this isn't set the plugin merely does nothing, rather than current behavior of preventing Datasette from starting entirely.
- `cookies` - list of cookies to pass through. If left blank, passes everything.
- `ttl` - optional, defaults to 0. How long should Datasette cache the association between the cookies and the actor?

**Comment by simonw** [comment]
I started by rewriting the README to document the new design: https://github.com/simonw/datasette-auth-existing-cookies/blob/bf551dc6ab2b161fcc5d906770a4c6fc1256a053/README.md#configuration

**Comment by simonw** [comment]
Realized I need a fourth:

- `headers`: an optional list of other headers to forward to the API endpoint as query string parameters.
